version: '3.8'
services: 
  client:
    container_name: client-container
    restart: always
    build: ./client
    ports: 
      - "8080:8080"
    depends_on:
      - server
  server:
    container_name: server-container
    restart: always
    build: ./server
    environment:
      DB_NAME: books_db
      USER_NAME: root
      PASSWORD: ${MYSQL_ROOT_PASSWORD}
      HOSTNAME: mysql
    ports: 
      - "8081:8081"
    depends_on: 
      - db
  db:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose: 
      - "3308"
    ports: 
      - "3308:3306"
    volumes: 
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
